name: Compile JOSS Paper

on:
  push:
    branches:
      - joss
    paths:
      - 'paper/**'
      - '.github/workflows/compile-joss.yml'
  workflow_dispatch:

jobs:
  build-paper:
    runs-on: ubuntu-latest

    container:
      image: openjournals/whedon:latest  # Official Whedon Docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile paper
        run: |
          cd paper
          make

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper/paper.pdf

