name: tests

on:
  push:
    branches: [ main, master, Updates ]
  pull_request:
    branches: [ main, master, Updates ]

jobs:
  test:
    name: pytest (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          use-mamba: true

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          mamba install -c conda-forge gdal numpy scipy pandas netcdf4 pytz shapely timezonefinder xarray tqdm matplotlib-base pyqt
          pip install pytest coverage pytest-cov
          pip install -e . --no-deps

      - name: Run tests with coverage
        shell: bash -el {0}
        run: |
          pytest --cov=solweig_gpu --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
          verbose: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.os }}-py${{ matrix.python-version }}
          path: coverage.xml


